#!/bin/bash
# 🎨 Wacom Linux Tool - Universal Multi-Device Installer (TUI Edition)
# Supports ANY Wacom Tablet (X11) - Optimized for Multi-Monitor setups

set -e

# Colors for non-TUI output
BLUE='\033[0;34m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

SETTINGS_FILE="$HOME/.wacom_settings.env"
TITLE="Wacom Universal Linux Customizer"

# --- DEPENDENCY CHECK ---
# Determine script's absolute directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo -e "${BLUE}[1/4] Verificando dependencias...${NC}"
# Collect missing packages
missing_packages=()
if ! command -v whiptail &> /dev/null; then missing_packages+=(whiptail); fi
if ! command -v xsetwacom &> /dev/null; then missing_packages+=(xserver-xorg-input-wacom); fi
if ! command -v xrandr &> /dev/null; then missing_packages+=(x11-xserver-utils); fi
if ! command -v xdotool &> /dev/null; then missing_packages+=(xdotool); fi
if ! command -v bc &> /dev/null; then missing_packages+=(bc); fi
if [ ${#missing_packages[@]} -gt 0 ]; then
  sudo apt update && sudo apt install -y "${missing_packages[@]}"
fi

# --- TUI WIZARD ---
whiptail --title "$TITLE" --msgbox "Bienvenido al configurador UNIVERSAL de Wacom.\n\nEste asistente configurará automáticamente CUALQUIER tableta Wacom conectada y optimizará tu setup de monitores." 12 70

# 1. Orientation
HAND_OPT=$(whiptail --title "$TITLE" --menu "Selecciona tu mano dominante:" 12 60 2 \
    "1" "ZURDO (Rotación 180°)" \
    "2" "DIESTRO (Sin rotación)" 3>&1 1>&2 2>&3)

case $HAND_OPT in
    1) ROTATION="half" ;;
    *) ROTATION="none" ;;
esac

# 2. Button 2 (Lower)
BTN2_OPT=$(whiptail --title "$TITLE" --menu "Acción para el BOTÓN INFERIOR (Stylus):" 12 60 2 \
    "1" "Click Derecho (Normal)" \
    "2" "Click Medio (Scroll)" 3>&1 1>&2 2>&3)

case $BTN2_OPT in
    2) BTN2_ACT="2" ;;
    *) BTN2_ACT="3" ;;
esac

# 3. Button 3 (Upper)
BTN3_OPT=$(whiptail --title "$TITLE" --menu "Acción para el BOTÓN SUPERIOR (Stylus):" 12 60 2 \
    "1" "Multi-Acción (Toggle, Copiar, Pegar, Alt+Tab)" \
    "2" "Deshacer (Ctrl+Z)" 3>&1 1>&2 2>&3)

case $BTN3_OPT in
    2) BTN3_ACT="key +ctrl +z -z -ctrl" ;;
    *) BTN3_ACT="key F10" ;;
esac

# 4. MONITOR MAPPING
SCREENS=$(xrandr --listactivemonitors | grep "+" | awk '{print $4}')
SCREEN_LIST="ALL Escritorio_Completo"
for s in $SCREENS; do SCREEN_LIST="$SCREEN_LIST $s Monitor_Individual"; done
SCREEN_NAME=$(whiptail --title "$TITLE" --menu "Mapeo de Pantalla:\n¿A qué monitor quieres vincular tu tableta?" 15 70 6 $SCREEN_LIST 3>&1 1>&2 2>&3)
if [ -z "$SCREEN_NAME" ]; then SCREEN_NAME="ALL"; fi

# Save settings
cat <<EOF > "$SETTINGS_FILE"
# Wacom Settings generated by TUI installer
ROTATION="$ROTATION"
BUTTON_2="$BTN2_ACT"
BUTTON_3="$BTN3_ACT"
SCREEN="$SCREEN_NAME"
PRESSURE_CURVE="0 20 80 100"
EOF

# --- SYSTEM INSTALLATION ---

# 1. Copiar scripts
echo -e "${BLUE}[2/4] Desplegando scripts en tu carpeta personal...${NC}"
cp "$SCRIPT_DIR"/.wacom_config.sh "$SCRIPT_DIR"/.wacom_toggle.sh "$SCRIPT_DIR"/.wacom_udev_trigger.sh "$SCRIPT_DIR"/.wacom_button_logic.sh "$SCRIPT_DIR"/.wacom_rotation_toggle.sh "$HOME/"
chmod +x "$HOME"/.wacom_*.sh

# 2. Regla udev
echo -e "${BLUE}[3/4] Configurando persistencia udev...${NC}"
RULE_PATH="/etc/udev/rules.d/99-wacom.rules"
echo 'ACTION=="add", SUBSYSTEM=="usb", ATTRS{idVendor}=="056a", RUN+="'"$HOME"/.wacom_udev_trigger.sh'"' | sudo tee "$RULE_PATH" > /dev/null
sudo udevadm control --reload-rules && sudo udevadm trigger

# 3. Autostart
mkdir -p "$HOME/.config/autostart"
cat <<EOF > "$HOME/.config/autostart/wacom-config.desktop"
[Desktop Entry]
Type=Application
Exec=$HOME/.wacom_config.sh
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
Name=Wacom Universal Config
EOF

# 4. CONFIGURACIÓN DE ATAJOS DE TECLADO
echo -e "${BLUE}[4/4] Configurando atajos de teclado automáticamente...${NC}"

# --- DETECCIÓN DE XFCE ---
if command -v xfconf-query &> /dev/null && [ "$XDG_CURRENT_DESKTOP" = "XFCE" ]; then
    echo -e "${YELLOW}🛠️ Detectado XFCE. Configurando atajos vía xfconf...${NC}"
    
    # Botón del Lápiz (F10) -> Lógica (Copy/Paste/Mode)
    xfconf-query -c xfce4-keyboard-shortcuts -p "/commands/custom/F10" -n -t string -s "$HOME/.wacom_button_logic.sh"
    
    # Teclado (Shift+F10) -> Rotación (Zurdo/Diestro)
    xfconf-query -c xfce4-keyboard-shortcuts -p "/commands/custom/<Shift>F10" -n -t string -s "$HOME/.wacom_rotation_toggle.sh"
    
    # Teclado (Shift+F11) -> Rotación (Por compatibilidad con la guía)
    xfconf-query -c xfce4-keyboard-shortcuts -p "/commands/custom/<Shift>F11" -n -t string -s "$HOME/.wacom_rotation_toggle.sh"
    
    echo -e "${GREEN}✅ Atajos de XFCE configurados correctamente.${NC}"
fi

# --- DETECCIÓN DE OPENBOX (LXDE) ---
RC_FILE="$HOME/.config/openbox/lxde-rc.xml"
[ ! -f "$RC_FILE" ] && RC_FILE="$HOME/.config/openbox/rc.xml"

if [ -f "$RC_FILE" ]; then
    if grep -q "wacom_button_logic.sh" "$RC_FILE"; then
        echo -e "${GREEN}✅ Los atajos de Wacom ya estaban configurados en Openbox.${NC}"
    else
        echo -e "${YELLOW}🛠️ Agregando atajos a $RC_FILE...${NC}"
        # Creamos el bloque XML de atajos corregido
        WACOM_KEYS="\n    <!-- Wacom Multi-Action Shortcuts (Added by Installer) -->\n    <keybind key=\"F10\">\n      <action name=\"Execute\"><command>$HOME/.wacom_button_logic.sh</command></action>\n    </keybind>\n    <keybind key=\"S-F10\">\n      <action name=\"Execute\"><command>$HOME/.wacom_rotation_toggle.sh</command></action>\n    </keybind>\n    <keybind key=\"S-F11\">\n      <action name=\"Execute\"><command>$HOME/.wacom_rotation_toggle.sh</command></action>\n    </keybind>"
        
        sed -i "/<\/keyboard>/i $WACOM_KEYS" "$RC_FILE"
        
        if command -v openbox &> /dev/null; then
            openbox --reconfigure
            echo -e "${GREEN}✅ Atajos de Openbox activados.${NC}"
        fi
    fi
fi

# --- APLICACIÓN INMEDIATA ---
echo -e "${BLUE}[5/5] Forzando aplicación de cambios ahora mismo...${NC}"
# Nos aseguramos de que el script de configuración tenga los permisos
chmod +x "$HOME"/.wacom_*.sh

# 6. Aplicación inmediata (detectar DISPLAY robusto)
# Intentamos usar DISPLAY actual; si no existe buscamos una sesión X11 activa
if [ -n "$DISPLAY" ]; then
    ACTIVE_DISPLAY="$DISPLAY"
else
    # Buscar una sesión X11 del usuario actual (ejemplo: loginctl)
    USER_SESS=$(loginctl list-sessions --no-legend | awk "$3==\"$USER\" && $4==\"x11\" {print $1; exit}")
    if [ -n "$USER_SESS" ]; then
        ACTIVE_DISPLAY=$(loginctl show-session "$USER_SESS" -p Display | cut -d= -f2)
    fi
fi

if [ -n "$ACTIVE_DISPLAY" ]; then
    export DISPLAY="$ACTIVE_DISPLAY"
    bash "$HOME/.wacom_config.sh"
    echo -e "${GREEN}✅ Configuración de hardware aplicada en DISPLAY=$ACTIVE_DISPLAY.${NC}"
else
    echo -e "${YELLOW}⚠️ No se encontró una sesión gráfica activa. Ejecuta ~/.wacom_config.sh manualmente una vez inicies sesión X11.${NC}"
fi

# Final instructions
whiptail --title "🎉 ¡TODO LISTO!" --msgbox "Tu Wacom ha sido configurada e integrada con tu escritorio.\n\nMonitor: $SCREEN_NAME\nOrientación: $ROTATION\n\nAtajos:\n- Botón Stylus: Multi-acción (F10)\n- Shift+F10: Cambiar Zurdo/Diestro (Rotación)\n- Shift+F11: Cambiar Zurdo/Diestro (Alternativo)\n\n¡La configuración ya ha sido aplicada!" 20 75
