#!/bin/bash
# 🎨 Wacom Linux Tool - Universal Installer (Dependency-Aware)
# Optimized for Wacom One (CTL-472)

set -e

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

SETTINGS_FILE="$HOME/.wacom_settings.env"

echo -e "${BLUE}====================================================${NC}"
echo -e "${GREEN}   🚀 WACOM LINUX CUSTOMIZER (Universal Edition)    ${NC}"
echo -e "${BLUE}====================================================${NC}"

# --- DEPENDENCY CHECK ---
echo -e "\n${BLUE}[0/4] Verificando dependencias del sistema...${NC}"

check_and_install() {
    local cmd=$1
    local package=$2
    if ! command -v "$cmd" &> /dev/null; then
        echo -e "${YELLOW}⚠️  Falta la dependencia: $package (comando: $cmd)${NC}"
        read -p "¿Deseas instalarla ahora? (requiere sudo) [S/n]: " yn
        case $yn in
            [Nn]*) echo -e "${RED}❌ Abortando: Se necesitan las dependencias para continuar.${NC}"; exit 1 ;;
            *) 
                echo -e "${BLUE}Instalando $package...${NC}"
                sudo apt update && sudo apt install -y "$package"
                ;;
        esac
    else
        echo -e "✅ $package ya está instalado."
    fi
}

# Verificamos los componentes clave
if command -v apt &> /dev/null; then
    check_and_install "xsetwacom" "xserver-xorg-input-wacom"
    check_and_install "notify-send" "libnotify-bin"
    check_and_install "xrandr" "x11-xserver-utils"
else
    echo -e "${YELLOW}⚠️  No se detectó un sistema basado en APT. Asegúrate de tener instalados:${NC}"
    echo "   - xserver-xorg-input-wacom"
    echo "   - libnotify-bin"
    echo "   - x11-xserver-utils"
fi

# --- CONFIGURATION WIZARD ---

# 1. Orientation
echo -e "\n${YELLOW}1. ¿Cuál es tu mano dominante?${NC}"
echo "1) Zurdo (Rotación 180°)"
echo "2) Diestro (Sin rotación)"
read -p "Opción [1-2]: " HAND_OPT
case $HAND_OPT in
    1) ROTATION="half" ;;
    *) ROTATION="none" ;;
esac

# 2. Button 2 (Lower)
echo -e "\n${YELLOW}2. ¿Qué acción quieres para el BOTÓN INFERIOR?${NC}"
echo "1) Click Derecho (Recomendado)"
echo "2) Click Medio (Scroll)"
read -p "Opción [1-2]: " BTN2_OPT
case $BTN2_OPT in
    2) BTN2_ACT="2" ;;
    *) BTN2_ACT="3" ;;
esac

# 3. Button 3 (Upper)
echo -e "\n${YELLOW}3. ¿Qué acción quieres para el BOTÓN SUPERIOR?${NC}"
echo "1) Cambiar modo (Tableta/Mouse) - Usa F12"
echo "2) Deshacer (Ctrl+Z)"
read -p "Opción [1-2]: " BTN3_OPT
case $BTN3_OPT in
    2) BTN3_ACT="key +ctrl +z -z -ctrl" ;;
    *) BTN3_ACT="key F12" ;;
esac

# 4. Display detection
echo -e "\n${YELLOW}4. Detectando pantallas disponibles...${NC}"
xrandr --listactivemonitors | grep "+" | awk '{print $4}'
read -p "Escribe el nombre de tu pantalla (ej: LVDS-1, HDMI-1): " SCREEN_NAME
if [ -z "$SCREEN_NAME" ]; then SCREEN_NAME="LVDS-1"; fi

# Save settings to .env file
cat <<EOF > "$SETTINGS_FILE"
# Wacom Settings generated by install.sh
DEVICE_NAME="Wacom One by Wacom S Pen stylus"
ROTATION="$ROTATION"
BUTTON_2="$BTN2_ACT"
BUTTON_3="$BTN3_ACT"
SCREEN="$SCREEN_NAME"
PRESSURE_CURVE="0 20 80 100"
EOF

# --- SYSTEM INSTALLATION ---

echo -e "\n${BLUE}[1/3] Instalando scripts en $HOME...${NC}"
cp .wacom_config.sh .wacom_toggle.sh .wacom_udev_trigger.sh "$HOME/"
chmod +x "$HOME"/.wacom_*.sh

echo -e "\n${BLUE}[2/3] Configurando persistencia (udev rule)...${NC}"
RULE_PATH="/etc/udev/rules.d/99-wacom.rules"
echo 'ACTION=="add", SUBSYSTEM=="usb", ATTR{idVendor}=="056a", ATTR{idProduct}=="037a", RUN+="'"$HOME"/.wacom_udev_trigger.sh'"' | sudo tee "$RULE_PATH" > /dev/null
sudo udevadm control --reload-rules && sudo udevadm trigger

echo -e "\n${BLUE}[3/3] Configurando Inicio Automático Universal (XDG)...${NC}"
mkdir -p "$HOME/.config/autostart"
cat <<EOF > "$HOME/.config/autostart/wacom-config.desktop"
[Desktop Entry]
Type=Application
Exec=$HOME/.wacom_config.sh
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
Name[en_US]=Wacom Config
Name=Wacom Config
Comment=Apply custom Wacom settings on login
EOF
echo "✅ Archivo .desktop creado en ~/.config/autostart/"

# --- DESKTOP ENVIRONMENT DETECTION ---
DE=${XDG_CURRENT_DESKTOP:-Unknown}
echo -e "\n${BLUE}====================================================${NC}"
echo -e "${YELLOW}🔍 DETECTADO ENTORNO: $DE${NC}"
echo -e "Para activar el botón de 'Toggle', configurá el atajo de teclado:"

case "$DE" in
    *GNOME*)
        echo "Go to: Settings -> Keyboard -> Keyboard Shortcuts -> Custom Shortcuts"
        echo "Command: $HOME/.wacom_toggle.sh | Key: F12"
        ;;
    *KDE*)
        echo "Go to: System Settings -> Shortcuts -> Custom Shortcuts"
        echo "Action: $HOME/.wacom_toggle.sh | Shortcut: F12"
        ;;
    *XFCE*)
        echo "Go to: Settings -> Keyboard -> Application Shortcuts"
        echo "Command: $HOME/.wacom_toggle.sh | Key: F12"
        ;;
    *LXDE*)
        echo "Edit: ~/.config/openbox/lxde-rc.xml"
        echo "Add <keybind key='F12'> with action Execute command $HOME/.wacom_toggle.sh"
        ;;
    *)
        echo "Configure a Custom Shortcut for F12 to run: $HOME/.wacom_toggle.sh"
        ;;
esac

echo -e "\n${GREEN}🎉 ¡INSTALACIÓN COMPLETADA!${NC}"
echo -e "${BLUE}====================================================${NC}"
