#!/bin/bash
# 🎨 Wacom Linux Tool - Professional TUI Installer
# Optimized for Wacom One (CTL-472)

set -e

# Colors for non-TUI output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m'

SETTINGS_FILE="$HOME/.wacom_settings.env"
TITLE="Wacom Linux Customizer"

# --- HELPER FUNCTIONS ---

show_msg() {
    whiptail --title "$TITLE" --msgbox "$1" 10 60
}

# --- DEPENDENCY CHECK ---
echo -e "${BLUE}Verificando dependencias esenciales...${NC}"

if ! command -v whiptail &> /dev/null; then
    echo "Instalando whiptail para la interfaz visual..."
    sudo apt update && sudo apt install -y whiptail
fi

# Verificamos componentes clave (silenciosamente para no romper la TUI)
if ! command -v xsetwacom &> /dev/null; then sudo apt update && sudo apt install -y xserver-xorg-input-wacom; fi
if ! command -v notify-send &> /dev/null; then sudo apt update && sudo apt install -y libnotify-bin; fi
if ! command -v xrandr &> /dev/null; then sudo apt update && sudo apt install -y x11-xserver-utils; fi

# --- TUI WIZARD ---

whiptail --title "$TITLE" --msgbox "Bienvenido al configurador profesional de Wacom One.\n\nEste asistente te ayudará a configurar tu tableta de forma persistente y profesional." 12 65

# 1. Orientation
HAND_OPT=$(whiptail --title "$TITLE" --menu "Selecciona tu mano dominante:" 12 60 2 \
    "1" "ZURDO (Rotación 180°)" \
    "2" "DIESTRO (Sin rotación)" 3>&1 1>&2 2>&3)

case $HAND_OPT in
    1) ROTATION="half" ;;
    *) ROTATION="none" ;;
esac

# 2. Button 2 (Lower)
BTN2_OPT=$(whiptail --title "$TITLE" --menu "Acción para el BOTÓN INFERIOR (Stylus):" 12 60 2 \
    "1" "Click Derecho (Normal)" \
    "2" "Click Medio (Scroll)" 3>&1 1>&2 2>&3)

case $BTN2_OPT in
    2) BTN2_ACT="2" ;;
    *) BTN2_ACT="3" ;;
esac

# 3. Button 3 (Upper)
BTN3_OPT=$(whiptail --title "$TITLE" --menu "Acción para el BOTÓN SUPERIOR (Stylus):" 12 60 2 \
    "1" "Modo Toggle (Tableta/Mouse)" \
    "2" "Deshacer (Ctrl+Z)" 3>&1 1>&2 2>&3)

case $BTN3_OPT in
    2) BTN3_ACT="key +ctrl +z -z -ctrl" ;;
    *) BTN3_ACT="key F12" ;;
esac

# 4. Display detection
SCREENS=$(xrandr --listactivemonitors | grep "+" | awk '{print $4}')
SCREEN_LIST=""
for s in $SCREENS; do
    SCREEN_LIST="$SCREEN_LIST $s Monitor"
done

SCREEN_NAME=$(whiptail --title "$TITLE" --menu "Selecciona la pantalla para mapear la Wacom:" 15 60 4 $SCREEN_LIST 3>&1 1>&2 2>&3)

if [ -z "$SCREEN_NAME" ]; then SCREEN_NAME="LVDS-1"; fi

# Save settings
cat <<EOF > "$SETTINGS_FILE"
# Wacom Settings generated by TUI install.sh
DEVICE_NAME="Wacom One by Wacom S Pen stylus"
ROTATION="$ROTATION"
BUTTON_2="$BTN2_ACT"
BUTTON_3="$BTN3_ACT"
SCREEN="$SCREEN_NAME"
PRESSURE_CURVE="0 20 80 100"
EOF

# --- SYSTEM INSTALLATION ---

echo -e "\n${BLUE}[1/3] Instalando scripts...${NC}"
cp .wacom_config.sh .wacom_toggle.sh .wacom_udev_trigger.sh "$HOME/"
chmod +x "$HOME"/.wacom_*.sh

echo -e "\n${BLUE}[2/3] Configurando persistencia udev...${NC}"
RULE_PATH="/etc/udev/rules.d/99-wacom.rules"
echo 'ACTION=="add", SUBSYSTEM=="usb", ATTR{idVendor}=="056a", ATTR{idProduct}=="037a", RUN+="'"$HOME"/.wacom_udev_trigger.sh'"' | sudo tee "$RULE_PATH" > /dev/null
sudo udevadm control --reload-rules && sudo udevadm trigger

echo -e "\n${BLUE}[3/3] Configurando Inicio Automático (XDG)...${NC}"
mkdir -p "$HOME/.config/autostart"
cat <<EOF > "$HOME/.config/autostart/wacom-config.desktop"
[Desktop Entry]
Type=Application
Exec=$HOME/.wacom_config.sh
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
Name=Wacom Config
Comment=Apply custom Wacom settings on login
EOF

# Apply now
"$HOME/.wacom_config.sh"

# Show final DE instructions in a message box
DE=${XDG_CURRENT_DESKTOP:-Unknown}
INSTRUCTIONS="Instalación completada con éxito.\n\nDetectado: $DE\n\nRECUERDA: Configura un atajo de teclado para F12 que ejecute:\n$HOME/.wacom_toggle.sh\n\nTu Wacom ya es persistente y profesional."

whiptail --title "🎉 ¡Éxito!" --msgbox "$INSTRUCTIONS" 15 65
